package bungieAPI

import "time"

type Application struct {

	// Unique ID assigned to the application
	ApplicationId int `json:"applicationId"`

	// Name of the application
	Name string `json:"name"`

	// URL used to pass the user's authorization code to the application
	RedirectUrl string `json:"redirectUrl"`

	// Link to website for the application where a user can learn more about the app.
	Link string `json:"link"`

	// Permissions the application needs to work
	Scope int64 `json:"scope"`

	// Value of the Origin header sent in requests generated by this application.
	Origin string `json:"origin"`

	// Current status of the application.
	Status ApplicationStatus `json:"status"`

	// Date the application was first added to our database.
	CreationDate time.Time `json:"creationDate"`

	// Date the application status last changed.
	StatusChanged time.Time `json:"statusChanged"`

	// Date the first time the application status entered the 'Public' status.
	FirstPublished time.Time `json:"firstPublished"`

	// List of team members who manage this application on Bungie.net. Will always consist of at least
	// the application owner.
	Team []ApplicationDeveloper `json:"team"`

	// An optional override for the Authorize view name.
	OverrideAuthorizeViewName string `json:"overrideAuthorizeViewName"`
}
